### ISSUE TITLE
not possible to assign const value

### ISSUE THREAD

**Issue by Freundschaft** [java-james/flutter_dotenv#10]
Hi there,

would it be possible to provide a method so I can assign an env to a constant? something like this

const apiHost = DotEnv().env['API_HOST'].toString()

**Comment by lchwe** [comment]
const variables must be a compile-time constant and DotEnv() is executed during runtime. just replace const with final

**Comment by java-james** [comment]
As mentioned above - Constants behave as compile time constants in dart.
Closing please let me know if the above suggestion did not resolve your issue.
