### ISSUE TITLE
Reverse engineering bug

### ISSUE THREAD

**Issue by yhbsh** [java-james/flutter_dotenv#100]
I was able to get all my .env files with all secrect keys from the apk, is it normal or when publishing to google play it will be different?

just do 
```console
unzip -l app.apk
```

under flutter_assets folder, you will find all assets, include .env files

**Comment by ccosnean** [comment]
@yhbsh yes, hence the "add the .env" into your `pubspec.yml` step. This approach is flawed in its core, sadly.

```yml
assets:
  - .env
```

**Comment by yhbsh** [comment]
> @yhbsh yes, hence the "add the .env" into your `pubspec.yml` step. This approach is flawed in its core, sadly.
> 
> ```yml
> assets:
>   - .env
> ```

That's kinda sad

**Comment by ccosnean** [comment]
@yhbsh agree. I found this package [envied](https://pub.dev/packages/envied) it uses the `build_runner` to take the `.env` contents and bake them into a generated file.

I added the `.env` and `.g.dart` files to .gitignore. And the package has a obfuscation feature. The secrets are still in the binary, and you could reverse engineer it, but more hidden... still looking for a better solution, if there is any...

looking for a solution with `--dart-define`.

**Comment by yhbsh** [comment]
> @yhbsh agree. I found this package [envied](https://pub.dev/packages/envied) it uses the `build_runner` to take the `.env` contents and bake them into a generated file.
> 
> I added the `.env` and `.g.dart` files to .gitignore. And the package has a obfuscation feature. The secrets are still in the binary, and you could reverse engineer it, but more hidden... still looking for a better solution, if there is any...
> 
> looking for a solution with `--dart-define`.
> 
> UPDATE:
> 
> Never mind, after more research `--dart-define` also bakes the the secrets into the binary (makes sense since it is a compile flag... 🤣 ), there's no way around it and it seems that the only mitigation for it is code obfuscation.

Were you able to extract the secrets from the binary? Using --dart-define

**Comment by ccosnean** [comment]
@yhbsh I haven't tried, i read it in [this article](https://codewithandrea.com/articles/flutter-api-keys-dart-define-env-files/#compiling-and-running-the-app-with---dart-define)

> The main advantage of using --dart-define is that we're no longer hardcoding sensitive keys in the source code.
> But when we compile our app, the keys are still going to be baked in in the release binary:


<img width="1115" alt="Screenshot 2024-06-04 at 22 27 24" src="https://github.com/java-james/flutter_dotenv/assets/22283233/ddee3c0f-9359-4dbd-ba28-19ec9c43ca43">
API keys and source code are combined to produce the release binary

This makes total sense that the keys are ending up in the final binary, in fact that is always the case with compiled binaries, unless you are downloading them from a remote source at runtime.

**Comment by yhbsh** [comment]
> @yhbsh I haven't tried, i read it in [this article](https://codewithandrea.com/articles/flutter-api-keys-dart-define-env-files/#compiling-and-running-the-app-with---dart-define)
> 
> > The main advantage of using --dart-define is that we're no longer hardcoding sensitive keys in the source code.
> > But when we compile our app, the keys are still going to be baked in in the release binary:
> 
> 
> <img width="1115" alt="Screenshot 2024-06-04 at 22 27 24" src="https://github.com/java-james/flutter_dotenv/assets/22283233/ddee3c0f-9359-4dbd-ba28-19ec9c43ca43">
> API keys and source code are combined to produce the release binary
> 
> This makes total sense that the keys are ending up in the final binary, in fact that is always the case with compiled binaries, unless you are downloading them from a remote source at runtime.

True, but I am not sure we can extract them easily from the release binary, please try and see where it goes, if that's true then obfuscating is a must

**Comment by ccosnean** [comment]
@yhbsh it is not easy, with obfuscation it is even harder. But still theoretically possible.

**Comment by maeddin** [comment]
Why not simply use `--dart-define-from-file=.env`? I don't quite understand the point of third-party packages here.

You can never completely prevent users from being able to read the secrets. Client secrets should only be an additional security hurdle.

**Comment by ccosnean** [comment]
> Why not simply use `--dart-define-from-file=.env`? I don't quite understand the point of third-party packages here.
> 
> You can never completely prevent users from being able to read the secrets. Client secrets should only be an additional security hurdle.

@maeddin you can use what's best for you. 

I use `flutter_dotenv` or [envied](https://pub.dev/packages/envied) now, cause it gives you insight on your env at build time, and you have a Typed env to use, that i find really handy.

With `--dart-define` you will know about a missing env var at Runtime, with `String.fromEnvironment`.

**Comment by maeddin** [comment]
> > Why not simply use `--dart-define-from-file=.env`? I don't quite understand the point of third-party packages here.
> > You can never completely prevent users from being able to read the secrets. Client secrets should only be an additional security hurdle.
> 
> @maeddin you can use what's best for you.
> 
> I use `flutter_dotenv` or [envied](https://pub.dev/packages/envied) now, cause it gives you insight on your env at build time, and you have a Typed env to use, that i find really handy.
> 
> With `--dart-define` you will know about a missing env var at Runtime, with `String.fromEnvironment`.

Why should Env variables be missing at runtime? They are defined in advance at compile time, so I don't see the point of defining them again at runtime.

**Comment by maeddin** [comment]
> > They are defined in advance at compile time
> 
> That's wrong. You can build you app without `--dart-define` flags and it will produce a valid build, with empty strings.
> 
> <img alt="Screenshot 2024-06-13 at 18 10 10" width="494" src="https://private-user-images.githubusercontent.com/22283233/339420996-91c486ef-83a0-497a-a780-e8369e59bb02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTE5MjUsIm5iZiI6MTcxODI5MTYyNSwicGF0aCI6Ii8yMjI4MzIzMy8zMzk0MjA5OTYtOTFjNDg2ZWYtODNhMC00OTdhLWE3ODAtZTgzNjllNTliYjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE1MTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NzI5NTgwZDgzYzNkOTI0NGJiMTE4M2RjZTRkYmIzYzE1MTQ3ZjVjNDgzNTM1NmQ1NTNlMDk1NjEwNDFhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CM1tOiB7jeLcw6C9Y4MzbG3mqDyT31b2-qTSCFefJrs">

Of course they are only defined at compile time if you use `const` variables for this (that's what the const keyword is for in the first place). And if the variable doesn't exist, an empty string is set, but I don't see how that contradicts my statement.

**Comment by maeddin** [comment]
> I use `flutter_dotenv` or [envied](https://pub.dev/packages/envied) now, cause it gives you insight on your env at build time, and you have a Typed env to use, that i find really handy.
> 
> With `--dart-define` you will know about a missing env var at Runtime, with `String.fromEnvironment`.

You can also use typed values with `int.fromEnvironment` and `bool.fromEnvironment` without parsing it yourself.

**Comment by ccosnean** [comment]
> [this comment](https://github.com/java-james/flutter_dotenv/issues/100#issuecomment-2165392205)
> With --dart-define you will know about a missing env var at Runtime, with String.fromEnvironment.

@maeddin again, with `--dart-define` you will know about a missing env only during runtime, when the `String.fromEnvironment` is executed.

`envied` uses `build_runner` and parses the variables before you run the app, while generating files. your app will not compile if the env is wrong. I find this really helpful, and that's why i use it.

**Comment by maeddin** [comment]
> > [this comment](https://github.com/java-james/flutter_dotenv/issues/100#issuecomment-2165392205)
> > With --dart-define you will know about a missing env var at Runtime, with String.fromEnvironment.
> 
> @maeddin again, with `--dart-define` you will know about a missing env only during runtime, when the `String.fromEnvironment` is executed.
> 
> `envied` uses `build_runner` and parses the variables before you run the app, while generating files. your app will not compile if the env is wrong. I find this really helpful, and that's why i use it.

Okay, now I understand what you mean. I thought you were referring to `flutter_dotenv`. My mistake.
I personally also find 'envied' more useful.

**Comment by java-james** [comment]
Hey everyone. Some good discussion on this thread. 

I've appended a section to the readme to be more explicit about the concern. See https://github.com/java-james/flutter_dotenv/blob/master/README.md#security-considerations

It's worth mentioning we could add obfuscation to this package to achieve making it harder to extract keys but it would come at a concern of giving the package consumers a false sense of security.

Related issues raised are
https://github.com/java-james/flutter_dotenv/issues/74
https://github.com/java-james/flutter_dotenv/issues/73
https://github.com/java-james/flutter_dotenv/issues/111

I am going to close the issues for now but if someone would like to discuss if there is value in  obfuscation or has another better idea please feel free to open or re open!
