### ISSUE TITLE
Consider export "errors.dart" file

### ISSUE THREAD

**Issue by myugen** [java-james/flutter_dotenv#108]
It would be nice to give the possibility to the developer to react to the different errors that a library may have. In the case of `flutter_dotenv` it is not possible since it does not export the errors.

**Comment by java-james** [comment]
Thanks for PR. Adding here for reference.
https://github.com/java-james/flutter_dotenv/pull/109

Plan to merge this as part of the explicit 3.X support

**Comment by java-james** [comment]
Merged PR - Plan to close this issue once released

**Comment by java-james** [comment]
Released in 5.2.0
