### ISSUE TITLE
.env is available in plain text via web!

### ISSUE THREAD

**Issue by lukyanov** [java-james/flutter_dotenv#111]
I recently decided to build and run a web version of my app. I was really surprised to find out that your env file is clearly visible in the Google Dev Console as plain text.

If this behavior is expected, it should be clearly stated in the documentation with a big WARNING sign.

.env is not for storing anything you can't expose to the public and this should be clearly communicated.

**Comment by java-james** [comment]
Environment variables used by your front end application at runtime cannot be reliably projected. They are required to be bundled into the code. Sensitive variables should be stored on your server/backend for example.

Please see related issue and discussion https://github.com/java-james/flutter_dotenv/issues/51#issuecomment-1040908470

**Comment by java-james** [comment]
I have added a new section to the readme. https://github.com/java-james/flutter_dotenv/blob/master/README.md#security-considerations

Obfuscation is something I would be happy to consider along as it's clear to the users of this and any frontend env lib that the bundled keys can be extracted and people don't have a false sense of security and therefore store sensitive info.

**Comment by java-james** [comment]
Thanks for raising the issue!

Related issues raised are
https://github.com/java-james/flutter_dotenv/issues/100
https://github.com/java-james/flutter_dotenv/issues/73
https://github.com/java-james/flutter_dotenv/issues/111

I am going to close the issues for now but if someone would like to discuss if there is value in obfuscation or has another better idea please feel free to open or re open!
