### ISSUE TITLE
Build fails on CI

### ISSUE THREAD

**Issue by esentis** [java-james/flutter_dotenv#13]
Is there any workaround to this ?
![analyzer](https://user-images.githubusercontent.com/52862600/90194920-fa454080-ddd0-11ea-869e-ce3ca3e24174.png)

**Comment by java-james** [comment]
Hi thanks for opening the issuer. Have you included .env as an asset:
```
Add the .env file to your assets bundle in pubspec.yaml

  assets:
    - .env
```

That version of flutter are you using?

**Comment by java-james** [comment]
Hi thanks for opening the issue.
You will want to create the dotenv file as part of your CI. Depending on the scale of your app/environment you may just check in the .env file. Alternately you could check in a .env.dev and rename it to .env as part of the dev CI for example.

**Comment by esentis** [comment]
Hey !
Yes the .env is included in the assets. The build doesn't fail locally, only when deployed on GitHub since .env is on .gitignore it is never published but the CI (flutter analyze) is still trying to find the assets specified on pubspec.yaml and obviously fails ^^
    Στις Παρασκευή, 14 Αυγούστου 2020, 04:38:19 π.μ. EEST, ο χρήστης James <notifications@github.com> έγραψε:  
 
 


Hi thanks for opening the issuer. Have you included .env as an asset:
Add the .env file to your assets bundle in pubspec.yaml

  assets:
    - .env

That version of flutter are you using?

**Comment by esentis** [comment]
Thanks for the tip. I found a workaround by creating the .env in a step before the flutter analyze, and now the build is working 👍

**Comment by mahdiyarz** [comment]
> Hi thanks for opening the issue. You will want to create the dotenv file as part of your CI. Depending on the scale of your app/environment you may just check in the .env file. Alternately you could check in a .env.dev and rename it to .env as part of the dev CI for example.

Would you please explain more about this solution? because CI will create own .env file and unfortunately I can't add anything to this file.

**Comment by esentis** [comment]
> > Hi thanks for opening the issue. You will want to create the dotenv file as part of your CI. Depending on the scale of your app/environment you may just check in the .env file. Alternately you could check in a .env.dev and rename it to .env as part of the dev CI for example.
> 
> 
> 
> Would you please explain more about this solution? because CI will create own .env file and unfortunately I can't add anything to this file.

An example of creating and adding content to the file 

'''script

cat > "/.env" <<EOF       PLACES_KEY_IOS_DEV=$PLACES_KEY_IOS_DEV    PLACES_KEY_ANDROID_DEV=$PLACES_KEY_ANDROID_DEV
EOF

'''
