### ISSUE TITLE
Project is looking for .env in assets folder

### ISSUE THREAD

**Issue by arualana** [java-james/flutter_dotenv#18]
I set up like this

```
assets:
    - .env
```

in my `pubspec.yaml `as specified in https://pub.dev/packages/flutter_dotenv but the project looks for the .env file inside the assets folder

**Comment by java-james** [comment]
This may have been an issue in previous flutter versions. I cannot reproduce in the latest flutter?

The `.env` file should be in the root of the project.
Please let me know if this is still and issue and I will reopen.
