### ISSUE TITLE
Any plans for null-safety?

### ISSUE THREAD

**Issue by asartalo** [java-james/flutter_dotenv#23]

**Comment by LuisGrt** [comment]
Hello, I am waiting for the same since I am trying to migrate my app already to null-safety. It would be nice to know if there is any plan to migrate this library.

**Comment by ngxingyu** [comment]
> Hello, I am waiting for the same since I am trying to migrate my app already to null-safety. It would be nice to know if there is any plan to migrate this library.

I actually created a pull request to implement null safety, perhaps you can try it out and see if there are any issues with it

**Comment by java-james** [comment]
Thanks for the issue.

See migration PR from @ngxingyu: https://github.com/java-james/flutter_dotenv/pull/24
This will be merged this evening. A release will be created once merged.

**Comment by java-james** [comment]
Thanks for your patience. The PR has been reviewed and merged. The prerelease has been published to the pub.dev as 4.0.0-nullsafety.0

If you are migrating your code base bring it for a spin. If you experience any issues please raise them and we can increment on the prerelease.
Thanks again @ngxingyu for spending time on the migration.

**Comment by LuisGrt** [comment]
> Thanks for your patience. The PR has been reviewed and merged. The prerelease has been published to the pub.dev as 4.0.0-nullsafety.0
> 
> If you are migrating your code base bring it for a spin. If you experience any issues please raise them and we can increment on the prerelease.
> Thanks again @ngxingyu for spending time on the migration.

**Thank you!**
