### ISSUE TITLE
Safari shows a blank page

### ISSUE THREAD

**Issue by silviamacis** [java-james/flutter_dotenv#26]
with Prerelease: 4.0.0-nullsafety.0 Safari doesn't load the web app. It works correctly with Chrome and with the 3.1.0 version.
<img width="1315" alt="Schermata 2021-03-17 alle 11 51 13" src="https://user-images.githubusercontent.com/62599609/111456372-3352e400-8717-11eb-9132-aaac1ebac546.png">

Dart SDK version: 2.12.1 (stable)

**Comment by java-james** [comment]
Thanks for opening this issue. I will try reproduce it with the vanilla example application and report back.

**Comment by justinenerio** [comment]
Any updates on this? Also experiencing this issue

**Comment by miyoyo** [comment]
[Safari does not support positive lookbehinds.](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group/51568859)
[This regex is not Safari compatible](https://github.com/java-james/flutter_dotenv/blob/master/lib/src/parser.dart#L10)

**Comment by ngxingyu** [comment]
I removed the use of positive lookbehind, yet to test with the Safari browser.

**Comment by java-james** [comment]
Thanks @miyoyo

@ngxingyu has authored PR #29 
I have released as 4.0.0-nullsafety.1 to pub.dev now.
Please check this fixes the issue for you.
