### ISSUE TITLE
[WEB] Add missing instructions regarding filename

### ISSUE THREAD

**Issue by aashutoshrathi** [java-james/flutter_dotenv#28]
Add instructions regarding filename when using the package for flutter web.

Instructions => `Don't use .env as name for config file, use a name without "." Eg: dotenv`

**Comment by smunozp** [comment]
yes please I was lucky to read this comment, other way i would spend hour figuring out why my app was okay on localhost and crashing on the hosting

**Comment by mellowcello77** [comment]
Please do mention it. It works on local builds for web, but not when deployed which really confuse me. In web console it doesn't even show what the null values might be, for my project at least. Cheers 🤞🏻 Thanks

**Comment by java-james** [comment]
👍 Thanks for this - Will include in instructions of the next release. Will close this issue once released.

**Comment by java-james** [comment]
@ngxingyu had resolved this in #34 
Awaiting release to pub dev can expect it early next week

**Comment by java-james** [comment]
This is now mentioned in the README.md. Please reopen the issue if you feel it isn't clear etc.

**Comment by khari998** [comment]
I tired using ```env``` instead of ```.env``` and it is not working for me. 

I also tried using ```dotenv``` instead of ```.env``` and no luck.

The package seems to look for ```.env``` when trying to access variables. 

Without using .env, I get the error ```Error while trying to load an asset: Failed to load asset at "assets/.env" (404)
Error: Instance of 'FileNotFoundError'``` 

Does anyone here have a clear guide to implementing this? This is very crucial for deployment builds. I think the package is currently not written to accept anything but ```.env``` but other people are finding success without the leading dot. If anyone could help with this, it would be greatly appreciated. 

Docs should be explicitly clear on what to do here because simply renaming the file won't prevent the error from the package when trying to run.

**Comment by khari998** [comment]
I looked in the package and under the load function I changed 

```dart
Future<void> load(
      {String fileName = '.env',
      Parser parser = const Parser(),
      Map<String, String> mergeWith = const {}}) async {
    clean();
    final linesFromFile = await _getEntriesFromFile(fileName);
    final linesFromMergeWith = mergeWith.entries
        .map((entry) => "${entry.key}=${entry.value}")
        .toList();
    final allLines = linesFromMergeWith..addAll(linesFromFile);
    final envEntries = parser.parse(allLines);
    _envMap.addAll(envEntries);
    _isInitialized = true;
  }
```

to 

```dart
Future<void> load(
      {String fileName = 'dotenv',
      Parser parser = const Parser(),
      Map<String, String> mergeWith = const {}}) async {
    clean();
    final linesFromFile = await _getEntriesFromFile(fileName);
    final linesFromMergeWith = mergeWith.entries
        .map((entry) => "${entry.key}=${entry.value}")
        .toList();
    final allLines = linesFromMergeWith..addAll(linesFromFile);
    final envEntries = parser.parse(allLines);
    _envMap.addAll(envEntries);
    _isInitialized = true;
  }
```

And it worked. On line 64, it only looks for one possible file name ".env" hence my error. It should be able to account for multiple types of env files including "env", "dotenv" and so on if we are going to be able to use this solution for flutter web because flutter web still compiles the package as is on the webserver and wont recognize ".env" as valid

**Comment by ngxingyu** [comment]
I believe you can change the name of the asset being parsed by replacing the default parameter, e.g. `dotenv.​load​(fileName​:​ ​"dir/dotenv"​);` will look for the file `dotenv` in folder `dir`. And you have to remember to add this into the pubspec.yaml file as well.

**Comment by khari998** [comment]
Oh okay that's what was confusing. I will use that parameter to change the name. I missed that in the documentation. Thank you @ngxingyu

**Comment by cardosopab** [comment]
Soooo, it was removed from the read me? lol happy I didn't waste too much time meandering my way to this post tho lol thanks!

**Comment by tesseractT** [comment]
> I believe you can change the name of the asset being parsed by replacing the default parameter, e.g. `dotenv.​load​(fileName​:​ ​"dir/dotenv"​);` will look for the file `dotenv` in folder `dir`. And you have to remember to add this into the pubspec.yaml file as well.

Hello where can we find the file to replace parameter

**Comment by kopianan** [comment]
> Add instructions regarding filename when using the package for flutter web.
> 
> Instructions => `Don't use .env as name for config file, use a name without "." Eg: dotenv`

this work for me dude.

**Comment by hasanradi93** [comment]
> Please do mention it. It works on local builds for web, but not when deployed which really confuse me. In web console it doesn't even show what the null values might be, for my project at least. Cheers 🤞🏻 Thanks

Are you found a solution my friend?
because i'm in the same trouble from yesterday.

**Comment by miguelmobilat** [comment]
> Add instructions regarding filename when using the package for flutter web.
> 
> Instructions => `Don't use .env as name for config file, use a name without "." Eg: dotenv`

not working
help

**Comment by eugenegous** [comment]
This setup worked for me...

pubspec.yaml
![pubspecyamls](https://github.com/java-james/flutter_dotenv/assets/8994511/81dbd888-02c1-41b0-b158-60e70f669f96)


main.dart - this now gets executed without the 404
![mains](https://github.com/java-james/flutter_dotenv/assets/8994511/f08447ae-1f09-47c3-9aa4-90c9102581b8)


flutter build web - after running `flutter build web`
![builds](https://github.com/java-james/flutter_dotenv/assets/8994511/dda7aae8-d58f-487a-bec7-2046a2111b3b)


browser
![browsers](https://github.com/java-james/flutter_dotenv/assets/8994511/e597cfba-0102-433f-910a-c13640f1e65a)

I hope this helps someone.

**Comment by zommerberg** [comment]
Nothing in this thread helped, looks like flutter still sucks for anything aside mobile.

**Comment by trust2065** [comment]
This will leak the secret stored in the `.env` :(

**Comment by AmerDje** [comment]
> This setup worked for me...
> 
> pubspec.yaml ![pubspecyamls](https://private-user-images.githubusercontent.com/8994511/332442599-81dbd888-02c1-41b0-b158-60e70f669f96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzcxNTIsIm5iZiI6MTcxOTczNjg1MiwicGF0aCI6Ii84OTk0NTExLzMzMjQ0MjU5OS04MWRiZDg4OC0wMmMxLTQxYjAtYjE1OC02MGU3MGY2NjlmOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDg0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDlmN2EwMTU2ZWJiMDU5Yjg1NDMwNjNjN2RhZTAwZTI1ZWQ0NDI3YTkxYzM5ZTQ2N2ZjMDFiNDU0YWY0YTIxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wdRmuJoWHIgSRdMy2izz3lc6jvo3Bi7uEyUNZTpFif8)
> 
> main.dart - this now gets executed without the 404 ![mains](https://private-user-images.githubusercontent.com/8994511/332442781-f08447ae-1f09-47c3-9aa4-90c9102581b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzcxNTIsIm5iZiI6MTcxOTczNjg1MiwicGF0aCI6Ii84OTk0NTExLzMzMjQ0Mjc4MS1mMDg0NDdhZS0xZjA5LTQ3YzMtOWFhNC05MGM5MTAyNTgxYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDg0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjliOTU0OTk4YmRjOWQ3ZjI2ZDViZjFhZWNhOWEzMGEyYzNkZTJiZWI2NWRlOGNjMTMzZjNkYWIxNzEyNDYyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fYgT6ASYU7LPB2YRw1GnYVwLfS8HyoKbsVdY-kMDcug)
> 
> flutter build web - after running `flutter build web` ![builds](https://private-user-images.githubusercontent.com/8994511/332442843-dda7aae8-d58f-487a-bec7-2046a2111b3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzcxNTIsIm5iZiI6MTcxOTczNjg1MiwicGF0aCI6Ii84OTk0NTExLzMzMjQ0Mjg0My1kZGE3YWFlOC1kNThmLTQ4N2EtYmVjNy0yMDQ2YTIxMTFiM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDg0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA5YTk4ZmRmOWFlNGI2N2E0YjRjMGMzNGIxOWI4MTBmZGMxNGE5NzY1ZmRmZmY5MjBkOWE4MzA3YWFiNmRhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.43DqzcHMcgQ1_fH2SkG8Ofje9QC40MQ4eCbrBOITJmQ)
> 
> browser ![browsers](https://private-user-images.githubusercontent.com/8994511/332443005-e597cfba-0102-433f-910a-c13640f1e65a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzcxNTIsIm5iZiI6MTcxOTczNjg1MiwicGF0aCI6Ii84OTk0NTExLzMzMjQ0MzAwNS1lNTk3Y2ZiYS0wMTAyLTQzM2YtOTEwYS1jMTM2NDBmMWU2NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDg0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMTE1NDc1NjZhODhhMGZkNzIyNTI4MmRjNTk0NmRlYjdlZmYyMDQwNDc3ZTU3MDQ1OGRmMTEwMjU1MzllNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uIg8pLh8mM-QoXzjBO3DXr6AxbU4Zq7lK_p-jUo9boE)
> 
> I hope this helps someone.

Thanks, this worked for me.

Note: You don't need to create an additional assets folder inside the original assets folder. Simply place the environment variables file directly in the original assets folder, like this:

``` sh
  assets:
    - dev.txt
```
In your main file:

``` dart
await dotenv.load(fileName: 'dev.txt');
```

**Comment by eugenegous** [comment]
> This will leak the secret stored in the `.env` :(

Very true. For storing secret I used [Flutter Secure Storage](https://pub.dev/packages/flutter_secure_storage).

**Comment by saravanan2k03** [comment]
![image](https://github.com/user-attachments/assets/d35d3415-11d6-4a64-ab5e-6019cc2c2df2)
![image](https://github.com/user-attachments/assets/f7c6615a-6d1f-49aa-bf7b-16b492ab16ed)
![image](https://github.com/user-attachments/assets/f278c516-4a71-48b8-a713-c115940b2c20)
-it work for me try this way

**Comment by saravanan2k03** [comment]
√ Built build\windows\x64\runner\Debug\sree_dashboard.exe
Connecting to VM Service at ws://127.0.0.1:55804/2Mpc3X_Cvjk=/ws
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'FileNotFoundError'
#0      DotEnv._getEntriesFromFile (package:flutter_dotenv/src/dotenv.dart:111:7)
<asynchronous suspension>
#1      DotEnv.load (package:flutter_dotenv/src/dotenv.dart:68:23)
<asynchronous suspension>
#2      main (package:sree_dashboard/main.dart:12:3)
<asynchronous suspension>

- how to fix on windows

**Comment by saravanan2k03** [comment]
![image](https://github.com/user-attachments/assets/09188ca3-4f2f-441e-a9cf-f9bafddaa43b)
- if you are running windows or other platform  you need to put the .env file on root dir 
- 
![image](https://github.com/user-attachments/assets/560dda98-e731-40d5-a9dd-1cc8975edab5)

**Comment by aprt06** [comment]
.env work fine on localhost but when I deploy on firebase I got error I have to change .env to dotenv and it works

**Comment by saravanan2k03** [comment]
I think if you are taking build it should ignore .env file so you manually add the .env file in build but renaming file .env to dotenv better option.👍

**Comment by sergnio** [comment]
+1 to using `dotenv` (or something else) rather than `.env`. For me these are the steps that worked, might be unnecessary for others!

1. Ensure `dotenv` is included in the `pubspec.yaml`, since my file is at the root folder
```
flutter:
  assets:
    - dotenv
```

2. Update the `fileName` property when doing `dotenv.load`
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load the environment variables from the root directory
  await dotenv.load(fileName: 'dotenv'); // Since the file is in the root folder
}
```

3. Test locally
4. Deploy!

**Comment by bytebender** [comment]
> I tired using `env` instead of `.env` and it is not working for me.
> 
> I also tried using `dotenv` instead of `.env` and no luck.
> 
> The package seems to look for `.env` when trying to access variables.
> 
> Without using .env, I get the error `Error while trying to load an asset: Failed to load asset at "assets/.env" (404) Error: Instance of 'FileNotFoundError'`
> 
> Does anyone here have a clear guide to implementing this? This is very crucial for deployment builds. I think the package is currently not written to accept anything but `.env` but other people are finding success without the leading dot. If anyone could help with this, it would be greatly appreciated.
> 
> Docs should be explicitly clear on what to do here because simply renaming the file won't prevent the error from the package when trying to run.

Did you add it to your assets under pubspec.yaml?

```yaml
  # To add assets to your application, add an assets section, like this:
  assets:
    - env
```
