### ISSUE TITLE
Updating key in .env file at runtime

### ISSUE THREAD

**Issue by alokyadavmdt** [java-james/flutter_dotenv#30]
Is there a way that key in .env can be updated. I have a scenario where when app runs first time then the user enter the server info and that i need to save to env file so next time its not required.

As i checked i didnt find any method which can update the file at runtime

**Comment by ngxingyu** [comment]
There is no way to edit the .env file within the assets bundle. Perhaps you can copy the file to the applications directory and use that file as the .env file, or use another package such as shared_preferences to store the user input.

**Comment by java-james** [comment]
Closing due to question being answered. Can re open if a feature request or similar required
