### ISSUE TITLE
[Request] Wrap dotenv methods (load, testLoad, get env) within a class for dotenv.dart

### ISSUE THREAD

**Issue by ngxingyu** [java-james/flutter_dotenv#32]
I would like to request for the methods within the dotenv.dart file to be wrapped within a DotEnv class (e.g. get env, load, clean, testLoad ...), and exposing an instance of the DotEnv class instead with `DotEnv dotenv = DotEnv()` for convenience.

This would allow for the DotEnv methods to be mocked, and also allow for multiple instances of envMaps to be created.
The implementation was changed to "Access via functions" in v.3.0.0, but I believe using singletons comes with more benefits than directly exposing the methods and is more versatile. What's your opinion on this?

The changes for end users would be:
```
// old
import 'package:flutter_dotenv/flutter_dotenv.dart' as dotenv; 
await dotenv.load();
dotenv.env;

// new
import 'package:flutter_dotenv/flutter_dotenv.dart';
// DotEnv dotenv = DotEnv() // included within dotenv.dart
await dotenv.load();
dotenv.env;
```

Here's my implementation of the changes for feedback:
https://github.com/ngxingyu/flutter_dotenv/commit/bcf47e589b92218c4074f726c20b32ce1a3d1345

**Comment by java-james** [comment]
> but I believe using singletons comes with more benefits than directly exposing the methods and is more versatile

I tend to agree with this. And it's a good point regarding mocking. I would be happy to accept this PR. From what I can see this would require a major version bump as the pattern for consumption changes?
