### ISSUE TITLE
Instance of 'NotInitializedError' in Flutter integration testing

### ISSUE THREAD

**Issue by SebghatYusuf** [java-james/flutter_dotenv#42]
When I'm trying to run integration testing, it's not working and I see this in a try catch block as error. 
Please let me know how I can handle this, any help would be highly appreciated :)

**Comment by ngxingyu** [comment]
Can you share a sample of your code? The error should not happen if you called something like `await dotenv.load(fileName: "assets/.env");` and set the path in pubspec.yaml, assuming the .env file in the assets folder.

**Comment by SebghatYusuf** [comment]
@ngxingyu sure, I will add code example, I have the .env file in my project directory not in assets folder but I'm adding it in my  `pubspec.yaml` file like this: 

```
  assets:
    - images/
    - .env
```

and I'm loading the dotenv file in my main function as below: 

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);
  // FirebaseCrashlytics.instance.crash();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  await dotenv.load(fileName: '.env');
  runApp(MyApp());
}

```

**Comment by ngxingyu** [comment]
Can you try changing your filename to assets/.env instead of .env?

**Comment by SebghatYusuf** [comment]
Okay
So, I need to move .env file to assets folder?

**Comment by ngxingyu** [comment]
Uh sorry ignore that last message. Just to confirm did you call `TestWidgetsFlutterBinding.ensureInitialized();` in your test file?

**Comment by SebghatYusuf** [comment]
> Uh sorry ignore that last message. Just to confirm did you call `TestWidgetsFlutterBinding.ensureInitialized();` in your test file?

Yeah, I did: 

```
main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("Testing app", (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    await tester.pumpAndSettle();
    await testVin(tester);
    await tester.pump();
  });
}
  ````

**Comment by SebghatYusuf** [comment]
Ohhh sorry, Let me just add `TestWidgetsFlutterBinding.ensureInitialized();`
but is it necessary when I have `IntegrationTestWidgetsFlutterBinding.ensureInitialized();` ?

**Comment by ngxingyu** [comment]
I haven't used the integration test package before, but `IntegrationTestWidgetsFlutterBinding.ensureInitialized();` should be sufficient. Did you call `await dotenv.load(fileName: '.env');` before your tests? Essentially the load method runs `rootBundle.loadString('.env')` and populates the dotenv object.

**Comment by SebghatYusuf** [comment]
@ngxingyu Actually I don't, I thought maybe because I'm calling it inside `MyApp()` widget, that would be enough. 
But I've tried that as well I've called `await dotenv.load(fileName: '.env');` before tests and still I wasn't able to read the dotenv file I've tried relative path as well, `await dotenv.load(fileName:'../env');` because the test file is inside intgration_test folder, but it didn't worked.

**Comment by ngxingyu** [comment]
I think `NotInitializedError` occurs when `dotenv.env` is called before the `dotenv.load` is called properly, and if the `dotenv.load` is called but fails it will throw `FileNotFoundError` or `EmptyEnvFileError`, so perhaps can try double checking if the load is called before .env. 
Alternatively, a possible workaround can be to directly import the .env file and do `dotenv.testLoad(fileInput: File('.env').readAsStringSync());`.

**Comment by SebghatYusuf** [comment]
@ngxingyu I just added `await dotenv.load('.env')` before ` IntegrationTestWidgetsFlutterBinding.ensureInitialized();` and now I don't get the `NotInitializedError` but still the value i'm retrieving form dotenv is null.

**Comment by SebghatYusuf** [comment]
ANY UPDATES??

**Comment by ngxingyu** [comment]
Did you try running TestWidgetsFlutterBinding.ensureInitialized();  before await dotenv.load('.env')?

**Comment by SebghatYusuf** [comment]
@ngxingyu 
Thank you, finally it worked.

**Comment by ziqq** [comment]
@ngxingyu Thank you, it worked.

**Comment by SimplicitySpace** [comment]
Thanks, I found this helpful
