### ISSUE TITLE
Dotenv not running on android

### ISSUE THREAD

**Issue by vinifig** [java-james/flutter_dotenv#54]
I'm currently facing some issues while running applications with DotEnv in my applications.
I checked the exported apk and aar, and the .env file is present there. But the application is throwing FileNotFound errors every time I start the application.

The app stays in the blank page. 

I've changed the library to get more detailed logs, but the only data about the error is:
```
Unable to load asset: .env
```

<img width="335" alt="image" src="https://user-images.githubusercontent.com/4935179/152197253-14c5ac6c-2a2c-4074-b351-4390c9377bfb.png">

**Comment by java-james** [comment]
Hey @vinifig Could you provide the initialisation code and the exact location you have created the .env file in?

**Comment by java-james** [comment]
Hi @vinifig due to no response I will close this issue. Please open and add details if this is still an issue for you.
