### ISSUE TITLE
does support web?

### ISSUE THREAD

**Issue by softmarshmallow** [java-james/flutter_dotenv#7]
does it support web?

**Comment by java-james** [comment]
Flutter web support can be achieved with a breaking change to remove the Platform.Environment merge. 

We should supply a helper function to additionally merge entries into the env map on load which should allow flutter users to merge platform environment variables for example while keeping this compatible with web.

**Comment by java-james** [comment]
Consider this high priority.
Will be fixing web support in the next release.

See: https://github.com/java-james/flutter_dotenv/issues/22

**Comment by java-james** [comment]
Web support has been added in [latest release](https://pub.dev/packages/flutter_dotenv).

If there are any issues on web please don't hesitate to create an new issue
