### ISSUE TITLE
Inquiries about security issues

### ISSUE THREAD

**Issue by Jay-flow** [java-james/flutter_dotenv#73]
I happened to read the blog post.

https://systemweakness.com/why-not-to-use-dotenv-on-flutter-5d3a07abc971

According to this article, the .env file appears to be readable.
I'm storing key security information here.
Is there a security problem depending on the blog post? I wonder if it's reliable or if there's a security problem, how can you secure it?

**Comment by java-james** [comment]
Thanks for raising the concern.
Please see https://github.com/java-james/flutter_dotenv/issues/51#issuecomment-1040908470 for a related discussion on this. In short, you shouldn't use .env on the client side to store sensitive data. Please get back to me if we are missing a point here, especially if you have something in mind we may have not thought of yet.

**Comment by Jay-flow** [comment]
Thank you for your comment.

Is there an alternative to how sensitive data is managed?

I would appreciate it if other people could suggest a good idea.

**Comment by java-james** [comment]
See suggestion on linked thread

> Operations that involve truly sensitive keys should be proxied through an API call to a service that can securely host and use these values.

There are env libraries that attempt to obfuscate your env variables. We could implement similar on this library, however, I think that would lull people into a false sense of security when in reality, no sensitive keys should be used on the front end of your application.

**Comment by java-james** [comment]
Thanks for raising it as an issue.

Related issues raised are
https://github.com/java-james/flutter_dotenv/issues/100
https://github.com/java-james/flutter_dotenv/issues/74
https://github.com/java-james/flutter_dotenv/issues/111

I am going to close the issues for now but if someone would like to discuss if there is value in  obfuscation or has another better idea please feel free to open or re open!

**Comment by sergembamba** [comment]
@java-james The issue has been marked as closed, but the proposed resolution may not be entirely sufficient. Even if the .env file is generated from managed secrets in CI, those values remain accessible once the APK is downloaded.

Should we consider implementing a local symmetric encryption mechanism before packaging these assets into the APK to better protect the secret variables?
