### ISSUE TITLE
 hide .env file on the web

### ISSUE THREAD

**Issue by rodrigorafaeldamaceno** [java-james/flutter_dotenv#74]
Hi, thanks for this package.

I'm using it in a web project, but I noticed that the .env file is available via inspector, I think because it's in assets, is there any way I can hide it?

<img width="667" alt="Screen Shot 2022-10-03 at 12 12 20" src="https://user-images.githubusercontent.com/15212018/193612802-45b81c1b-c7dd-4ede-8103-41f9632cb14b.png">

**Comment by Jay-flow** [comment]
Related issue https://github.com/java-james/flutter_dotenv/issues/51#issuecomment-1040908470

**Comment by kev-techi** [comment]
@rodrigorafaeldamaceno , you shouldn't put secrets on the frontend. It's an env file intended to put endpoints, tokens, flags that will always be visible to the frontend even if compiled into the code.

**Comment by java-james** [comment]
Hey everyone. Some good discussion on this thread. 

I've appended a section to the readme to be more explicit about the concern. See https://github.com/java-james/flutter_dotenv/blob/master/README.md#security-considerations

It's worth mentioning we could add obfuscation to this package to achieve making it harder to extract keys but it would come at a concern of giving the package consumers a false sense of security.

Related issues raised are
https://github.com/java-james/flutter_dotenv/issues/100
https://github.com/java-james/flutter_dotenv/issues/73
https://github.com/java-james/flutter_dotenv/issues/111

I am going to close the issues for now but if someone would like to discuss if there is value in  obfuscation or has another better idea please feel free to open or re open!
