### ISSUE TITLE
Security issue in release mode

### ISSUE THREAD

**Issue by muhammadkamel** [java-james/flutter_dotenv#87]
The ".env" file remains in the "flutter_assets" folder in the release after converting the APK file to a ZIP file and extracting it.

![Screenshot 2023-06-17 at 7 45 32 PM](https://github.com/java-james/flutter_dotenv/assets/17657941/d857d98d-7ac0-46d9-a53f-975aa7b4de5f)

**Comment by java-james** [comment]
Hey @muhammadkamel thanks for the issue. Please see my explanation on https://github.com/java-james/flutter_dotenv/issues/51#issuecomment-1040908470

This package is for managing front-end variables and is not intended for sensitive secrets.

**Comment by kev-techi** [comment]
@java-james , some way to put this as a big warning in the docs? I'm seeing a few open issues with developers who don't understand the difference between env and secrets.

**Comment by java-james** [comment]
@kev-techi Yep agree some learning info at the top of the readme should help developers understand and responsibly use this package

**Comment by java-james** [comment]
@kevtechi Added to readme in 5.2.1 :) 
Thanks for the suggestion.
