### ISSUE TITLE
where does the .env file go?

### ISSUE THREAD

**Issue by nyck33** [java-james/flutter_dotenv#88]
You need a tree diagram in your Readme so right away users know, "oh, that's where it goes".

**Comment by nyck33** [comment]
This don't work

![image](https://github.com/java-james/flutter_dotenv/assets/25189545/f6138e0f-dce3-49c3-bd90-ab99df3b7dde)


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

**Comment by zayKenyon** [comment]
There's a couple changes you need to make in-order to get this to work.

1. You need to place the `.env` file in the **root** of your project, see my image below:

![image](https://github.com/java-james/flutter_dotenv/assets/87788699/f3e321de-c967-49d5-91c9-08a0aef041eb)

2. Your `pubspec.yaml` should read as follows. People commonly get the indentation of `assets` wrong here so pay attention to your file.
```yml
flutter:
  uses-material-design: true
  assets:
    - .env
```

**Comment by zayKenyon** [comment]
If you're still having troubles, check out #72 .

**Comment by nyck33** [comment]
Thanks!
