### ISSUE TITLE
flutter_dotenv looking for env files in imaginary directory

### ISSUE THREAD

**Issue by Bus42** [java-james/flutter_dotenv#92]
I placed my env files in lib/env
This is where I load them in my main.dart
```dart

  await dotenv.load(
      fileName: kIsWeb ? 'lib/env/web.env' : 'lib/env/android.env');
```
Here's the assets section of my pubspec.yaml
```yaml
  assets:
    - lib/env/
    - lib/assets/images/
    - lib/assets/icons/
```
This is the error I get
`Error while trying to load an asset: Flutter Web engine failed to fetch "assets/lib/env/web.env". HTTP request succeeded, but the server responded with HTTP status 404.`

I've tried clearing my cache, and searching my entire codebase for where it's getting that from, and nothing. What gives?

**Comment by EnaEd** [comment]
the same issue when I deployed flutter app to IIS.
my pubspec.yaml
`flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config.env`
    and I had placed cofig file inside root
    
![image](https://github.com/java-james/flutter_dotenv/assets/35765131/fef91b63-2d68-453b-af9b-a742414a8cc1)

Also not working with .env as file name
Any thoughts?

**Comment by Bus42** [comment]
It seems to be a "random" error with the Flutter engine. Out of nowhere, one of my apps started looking for a file in a directory that does not exist and is not in my pubspec.yaml.

```
Error while trying to load an asset: Flutter Web engine failed to fetch "assets/error_messages.json". HTTP request succeeded, but the server responded with HTTP status 404.
```

```
assets:
  - lib/src/utils/error_messages.json
```

**Comment by Bus42** [comment]
I've tried clearing my cache and everything else I can imagine, it just won't look for the file where I tell it to.

**Comment by Bus42** [comment]
Basically, this doesn't seem to be a dotenv error.
