### ISSUE TITLE
Error while trying to load an asset: Flutter Web engine failed to fetch "assets/.env". HTTP request succeeded, but the server responded with HTTP status 404.

### ISSUE THREAD

**Issue by YawarOsman** [java-james/flutter_dotenv#95]
When i try to load my `.env` file it shows this error:

```
Error while trying to load an asset: Flutter Web engine failed to fetch "assets/.env". HTTP request succeeded, but the server responded with HTTP status 404.

```

I have added this too:
```
  assets:
    - .env
```

**Comment by nghiashiyi** [comment]
> When i try to load my `.env` file it shows this error:
> 
> ```
> Error while trying to load an asset: Flutter Web engine failed to fetch "assets/.env". HTTP request succeeded, but the server responded with HTTP status 404.
> ```
> 
> I have added this too:
> 
> ```
>   assets:
>     - .env
> ```

Same issue

**Comment by MilanHofmann** [comment]
Same for me.

`Error while trying to load an asset: Flutter Web engine failed to fetch "assets/assets/dotenv". HTTP request succeeded, but the server responded with HTTP status 404.`

But my flutter web service worker has `"assets/assets/dotenv": "4ef2f78446edff171436088341b541e3"` in it's resources...?

**Comment by wj-yang-pro** [comment]
Same here,

I found that changing the file name to 'env' works on firebase web projects

https://{host}/assets/.env -> http 404
https://{host}/assets/env -> http 200

not sure if it is a firebase hosting problem


overall, I need to change 
env filename: `.env` to `env`
pubspec.yaml 
```
  assets:
    - env
```
and
code:
``` 
await dotevn.load(fileName: 'env')
```

**Comment by heki-dm** [comment]
I encountered the same problem.

There was a hidden file setting in `firebase.json`, so I tried excluding it, but the result was the same.
However, I don't know if the setting method is correct.

Before
```json
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",  // include .env file?
      "**/node_modules/**"
    ]
  }
```
After
```json
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "!.env",  // add
      "**/node_modules/**"
    ]
  }
```

**Comment by ayaosama14** [comment]
> Same for me.
> 
> `Error while trying to load an asset: Flutter Web engine failed to fetch "assets/assets/name.json". HTTP request succeeded, but the server responded with HTTP status 404.`

**Comment by lmanliang** [comment]
Files that start with a dot (.) are considered a security concern on most web servers, such as Apache and Nginx, and access is typically restricted. This is not an issue with Flutter dotenv, but rather a default limitation of the web server.
